version: '2'
services:
    generateurassur-app:
        image: generateurassur
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://generateurassur-mysql:3306/generateurassur?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    generateurassur-mysql:
        extends:
            file: mysql.yml
            service: generateurassur-mysql
